name: CI
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8

      - run: pnpm install

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: pnpm test

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: pnpm lint