name: CI
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8

      - name: 'Create env file'
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
          echo SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} >> .env
          echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env

      - run: pnpm install

      - run: pnpm test

      - run: pnpm lint